title: RIF Name Service Docs
description: >
  RNS provides an architecture which enables the identification
  of blockchain addresses by human-readable names.

rss: rss

breadcrumbs:
  root:
    hide: true
    image: false

permalink: pretty

repository: rnsdomains/rnsdomains.github.io
domain: docs.rns.rifos.org

highlighter: rouge

plugins:
 - jekyll-last-modified-at
 - jekyll-feed
 - jekyll-github-metadata
