title: RSK Docs
description: >
  RSK is the first open source Smart Contract platform secured by the Bitcoin Network. RSK adds value and expand functionality to the Bitcoin ecosystem by providing smart contracts and greater scalability.

rss: rss

breadcrumbs:
  root:
    hide: false
    image: false

permalink: pretty

repository: rootstock/developers
domain: rsk.co

highlighter: rouge

plugins:
 - jekyll-last-modified-at
 - jekyll-feed
 - jekyll-github-metadata
 - jekyll-sitemap
