title: RSK Developer Portal

description: >
  RSK is the first open source Smart Contract platform secured by the
  Bitcoin Network. RSK adds value and expands the functionality of the
  Bitcoin ecosystem by providing smart contracts and greater scalability.

collections:
  quick-start:
    sort_by: collection_order
    output: true
  rsk:
    sort_by: collection_order
    output: true

rss: rss

breadcrumbs:
  root:
    hide: true
    image: false

permalink: pretty

repository: rsksmart/rsksmart.github.io

domain: "developers.rsk.co"
url: "https://developers.rsk.co"
redirect_base: ""
redirect_time: 0

highlighter: rouge

toc:
  min_level: 2
  max_level: 2
  list_class: on_this_page
  sublist_class: ''
  item_class: ''
  item_prefix: 'on_this_page-'

github: [metadata]

exclude:
  - .jekyll-cache
  - .bundle
  - vendor
  - assets/img/windowsInstall/
  - node_modules

plugins:
 - jekyll-last-modified-at
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-toc
 - jemoji
