version: 2.1

jobs:

  docs_build:
    working_directory: ~/tmp
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - run:
          name: Env Vars
          command: |
            echo "export BUNDLE_PATH=~/tmp/vendor/bundle" >> $BASH_ENV
            echo "export GEM_HOME=~/tmp/vendor/bundle" >> $BASH_ENV

      - checkout

      # Reject Gemfile.lock changes except in specific scenarios
      - run:
          name: "Checking for changes in ruby gems lock file"
          command: |
            ./.circleci/check-ruby-gems-lock-file-changed.sh

      # Restore bundle cache
      - restore_cache:
          keys:
            - v2-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
            - v2-gem-cache-{{ arch }}-

      - run:
          name: Set up bundler
          command: |
            echo "BUNDLE_PATH=${BUNDLE_PATH}"
            echo "GEM_HOME=${GEM_HOME}"
            gem install bundler
            bundle config set path "${BUNDLE_PATH}"
            ruby -v && bundle -v

      - run:
          name: Set up bundle gems
          command: |
            bundle check || bundle install --jobs=4 --retry=3
            bundle exec jekyll -v

      # Store bundle cache
      - save_cache:
          key: v2-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/tmp/vendor/bundle

      - run:
          name: Tests
          command: |
            bundle exec rake test

      # so that results from docs_build may be used in docs_deploy
      - persist_to_workspace:
          root: ./
          paths: _site

  docs_deploy:
    docker:
      - image: node:12.16.1
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Disable jekyll builds"
          command: touch ./_site/.nojekyll
      - run:
          name: Configure git
          command: |
            git config user.email "bguiz@users.noreply.github.com"
            git config user.name "bguiz"
      - add_ssh_keys:
          fingerprints:
            - "b6:c7:47:67:68:72:69:72:e7:57:4b:b0:2e:47:28:6c"
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages@2.0.1 --dotfiles --message "[skip ci] published at $( date --iso-8601=seconds )" --dist ./_site

workflows:
  version: 2
  build:
    jobs:
      - docs_build
      - docs_deploy:
          requires:
            - docs_build
          filters:
            branches:
              only: master
